/**
 * Format v16 — Fully parametric fast format
 *
 * Generalizes all previous format variants by accepting the same options as the
 * normal `format` function and generating a hardcoded function for those exact
 * parameters. No runtime branching on `long`, `length`, `format`, or `language`:
 * all are baked into the generated bytecode at build time.
 *
 * API:
 *   const fmt = buildFastFormat({ length: 3, language: LANGUAGES.en, format: 'HMS', long: false });
 *   fmt(5400000);  // '1h 30m'
 *   fmt(-1234);    // '- 1s'
 *
 * The returned function signature is `(ms: number) => string | null`.
 * Unlike previous variants there is no `long?` parameter — that value is fixed.
 *
 * Code generation strategy:
 *
 *   length === 1:
 *     Pure early-return if-chain (same as v15s/v15l). No remaining tracking,
 *     no counter, no string accumulation. Smallest possible bytecode per
 *     language/format combination → TurboFan eligible when called through a
 *     thin wrapper (same mechanism as v11).
 *
 *   length > 1:
 *     Accumulation body: `var r,s,c` + per-unit `if(c<length && r>=T)` blocks.
 *     Since `length` is a compile-time constant, the `c<N` literal is inlined
 *     rather than read from a variable. The `r -= v * T` deductions let the
 *     generated function produce correct multi-unit output (e.g. "2h 30m 15s").
 *
 * Defaults match `format/normal.ts`:
 *   language: LANGUAGES.en
 *   long:     false
 *   length:   1  ← default is 1 (single-unit, fastest) unlike normal which defaults to 3
 *   format:   'YMoDHMSMs'
 */
import { TIMES, Language, type Unit } from '../../core/index.ts';
import { LANGUAGES } from '../../core/languages.ts';
import { craftFunction } from '../../utils/craft.ts';
import type { ValidFormat } from '../normal.ts';

export type FastFormatFn = (ms: number) => string | null;

const FORMATS_REGEX = /Mo|Ms|Y|W|D|H|M|S/gu;

interface BuildOptions {
	long?: boolean;
	length?: number;
	language?: Language;
	format?: ValidFormat;
}

function escapeString(value: string): string {
	return value.replace(/\\/gu, '\\\\').replace(/'/gu, '\\x27');
}

function notation(language: Language, unit: Unit, long: boolean, singular: boolean): string {
	return escapeString(language.getNotation(unit, long, singular));
}

// ─── length === 1 ─────────────────────────────────────────────────────────────
// Pure early-return if-chain. No counter, no accumulation, no remaining tracking.

function buildSingleUnitBody(units: Unit[], language: Language, long: boolean): string {
	let branches = '';

	for (const unit of units) {
		const t = TIMES[unit];
		const sing = notation(language, unit, long, true);
		const plur = notation(language, unit, long, false);
		const expr = t === 1 ? 'Math.trunc(a)' : `Math.trunc(a/${t})`;

		if (sing === plur)
			branches += `if(a>=${t})return p+${expr}+'${sing}';`;
		else
			branches += `if(a>=${t}){var v=${expr};return p+v+(v===1?'${sing}':'${plur}');}`;
	}

	const zero = notation(language, units.at(-1)!, long, false);
	branches += `return '0${zero}';`;

	return 'if(typeof ms!==\'number\'||!Number.isFinite(ms))return null;' +
	  `var neg=ms<0;var a=neg?-ms:ms;var p=neg?'- ':'';${
	  	branches}`;
}

// ─── length > 1 ───────────────────────────────────────────────────────────────
// Accumulation body. `c` is the match counter, `r` is remaining ms, `s` the output.

function buildMultiUnitBody(units: Unit[], language: Language, long: boolean, length: number): string {
	// Clamp length to the number of available units — avoids unreachable counter checks
	const cap = Math.min(length, units.length);
	let branches = '';

	for (let i = 0; i < units.length; i++) {
		const unit = units[i]!;
		const t = TIMES[unit];
		const sing = notation(language, unit, long, true);
		const plur = notation(language, unit, long, false);
		const expr = t === 1 ? 'Math.trunc(r)' : `Math.trunc(r/${t})`;
		const deduct = t === 1 ? 'r-=v;' : `r-=v*${t};`;
		// First unit never needs a counter guard (c is always 0 at that point)
		const guard = i === 0 ? '' : `c<${cap}&&`;

		if (sing === plur)
			branches += `if(${guard}r>=${t}){var v=${expr};${deduct}s+=v+'${sing} ';c++;}`;
		else
			branches += `if(${guard}r>=${t}){var v=${expr};${deduct}s+=v+(v===1?'${sing}':'${plur}')+' ';c++;}`;
	}

	const zero = notation(language, units.at(-1)!, long, false);

	return 'if(typeof ms!==\'number\'||!Number.isFinite(ms))return null;' +
	  'var neg=ms<0;var a=neg?-ms:ms;var p=neg?\'- \':\'\';' +
	  `var r=a,s='',c=0;${
	  	branches
	  }if(s==='')return '0${zero}';` +
	  'return p+s.trimEnd();';
}

// ─── Builder ──────────────────────────────────────────────────────────────────

export function buildFastFormat(options: BuildOptions = {}): FastFormatFn {
	const long = options.long ?? false;
	const length = options.length ?? 1;
	const language = options.language ?? LANGUAGES.en;
	const formatStr = options.format ?? 'YMoDHMSMs';

	if (typeof long !== 'boolean')
		throw new Error("'long' should be a boolean");
	if (typeof length !== 'number' || !Number.isFinite(length) || length < 1 || length > 8)
		throw new Error("'length' should be a number between 1 and 8");
	if (!(language instanceof Language))
		throw new Error("'language' should be a Language instance");
	if (typeof formatStr !== 'string')
		throw new Error("'format' should be a non-empty string");

	// Reset lastIndex before using the global regex
	FORMATS_REGEX.lastIndex = 0;
	const units = formatStr.match(FORMATS_REGEX) as Unit[] | null;
	if (!units || units.length === 0)
		throw new Error('invalid format');

	const body = length === 1 ?
		buildSingleUnitBody(units, language, long) :
		buildMultiUnitBody(units, language, long, length);

	return craftFunction<FastFormatFn>('formatFn', [ 'ms' ], body, {});
}
