/**
 * Format v10 — v6 with Math.trunc instead of Math.floor
 *
 * Single change from v6: replace `Math.floor(a/t)` with `Math.trunc(a/t)` in all
 * division expressions.
 *
 * Why it's correct: `a` is always non-negative (`a = neg ? -ms : ms`), so
 * `Math.floor(x) === Math.trunc(x)` for all x >= 0. The semantics are identical.
 *
 * Why it may be faster: `Math.floor` is a built-in function call with a full
 * CallBuiltin sequence in the generated bytecode. `Math.trunc` maps directly to a
 * single machine instruction in TurboFan/Maglev (ROUNDSD with truncation mode).
 * The result stays as float64 (not int32), so there's no risk of overflow for large
 * millisecond values (unlike `|0` which is int32 only).
 *
 * V8 does recognise Math.floor in many cases and can elide the call after warmup,
 * but explicit Math.trunc makes the intent unambiguous and may lower the bytecode
 * instruction count enough to affect JIT tier selection.
 */
import { getUnitNotation } from '../utils/language.ts';
import { TIMES, UNITS, type Language } from '../../src/core/index.ts';
import { craftFunction } from '../utils/craft.ts';

type FastFormatFunction = (miliseconds: number, long?: boolean) => string | null;

function escapeString(value: string): string {
	return value.replace(/\\/gu, '\\\\').replace(/'/gu, '\\x27');
}

function buildBranches(language: Language, long: boolean): string {
	let body = '';

	for (const unit of UNITS) {
		const t = TIMES[unit];
		const sing = escapeString(getUnitNotation(language, unit, long, true));
		const plur = escapeString(getUnitNotation(language, unit, long, false));
		const expr = t === 1 ? 'Math.trunc(a)' : `Math.trunc(a/${t})`;

		if (sing === plur)
			body += `if(a>=${t})return p+${expr}+'${sing}';`;
		else
			body += `if(a>=${t}){var v=${expr};return p+v+(v===1?'${sing}':'${plur}');}`;
	}

	const zero = escapeString(getUnitNotation(language, UNITS.at(-1)!, long, false));
	body += `return '0${zero}';`;
	return body;
}

function buildMergedBody(language: Language): string {
	const shortBranches = buildBranches(language, false);
	const longBranches = buildBranches(language, true);
	return `if(typeof ms!=='number'||!Number.isFinite(ms))return null;var neg=ms<0;var a=neg?-ms:ms;var p=neg?'- ':'';if(!long){${shortBranches}}else{${longBranches}}`;
}

export function buildFastFormat(language: Language): FastFormatFunction {
	return craftFunction<FastFormatFunction>('formatFn', [ 'ms', 'long' ], buildMergedBody(language), {});
}
