/**
 * Parse v25 — Flat lookup table via `craftFunction`.
 *
 * Replaces the nested trie `switch` of v18 with a flat list of independent `if` checks,
 * one per (notation × case-variant). The code is generated by `generateLookupCode` in
 * `src/utils/notation.ts` and embedded as a labeled `match:{}` block.
 *
 * Why flat `if` beats nested `switch`:
 *   - Each check is data-independent from the others → CPU can speculate/pipeline them.
 *   - V8 Maglev compiles the flat structure with optimal branch prediction.
 *   - Code size stays under Maglev's threshold for English/Spanish dicts.
 */
import type { Language } from '../core/index.ts';
import { collectCharRanges, buildBoundaryTable } from '../utils/trie.ts';
import type { ParseFunction } from '../core/types.ts';
import { craftFunction } from '../utils/craft.ts';
import { extractNotations, generateLookupCode } from '../utils/notation.ts';

export function buildParse(language: Language): ParseFunction {
	const notations = extractNotations(language.dict);
	const ranges = collectCharRanges(language.dict, true);
	const boundaryArr = buildBoundaryTable(ranges);
	// 5 tabs = nesting level inside: while > if(digit) > if(pv===pv) > if(i<len) > else > match:
	const lookupCode = generateLookupCode(notations, '\t\t\t\t\t');

	// ─── Generated function source ────────────────────────────────────────────
	// Variables captured from context (via craftFunction closure):
	//   BOUND — Uint8Array[128]: BOUND[c]=1 means c is a valid notation-start/boundary char
	//
	// Runtime variables:
	//   s, len — string alias and its length
	//   si     — start index after leading spaces (and optional sign)
	//   neg    — true if the string started with '-'
	//   v      — accumulated result (sum of parsedValue * multiplier per token)
	//   mc     — match count (0 = no notation matched → fall back to Number())
	//   i      — current scan position
	//   c      — char code at i
	//   pv     — parsed numeric value for the current token
	//   c0     — first char of the potential notation (after the number + spaces)

	const source = `
		// ─── guard: type check and empty string ──────────────────────────────────
		if (typeof str !== 'string' || str === '') return null;

		var s = str, len = s.length;

		// ─── skip leading spaces, detect optional leading sign ────────────────────
		var si = 0;
		while (si < len && s.charCodeAt(si) === 32) si++;  // 32 = ' '
		var neg = s.charCodeAt(si) === 45;                  // 45 = '-'
		if (neg) {
			si++;
			while (si < len && s.charCodeAt(si) === 32) si++;
		}

		// ─── early exit: first meaningful char is not '-', digit or '.' ──────────
		// If so, the whole string must be a bare number like "100" → Number() directly.
		var fc = s.charCodeAt(si);
		if (fc !== 45 && (fc - 48 >>> 0) >= 10 && fc !== 46) {
			// (fc-48)>>>0 >= 10  ↔  fc NOT in '0'(48)–'9'(57)
			// 45='-', 46='.', 48='0'…57='9'
			var n = +str;
			return n !== n ? null : n;  // n!==n iff Number() returned NaN
		}

		var v = 0,   // accumulated result
		    mc = 0,  // notation match count
		    i = si;  // scan position

		// ─── main scan loop ───────────────────────────────────────────────────────
		while (i < len) {
			var c = s.charCodeAt(i);

			if ((c - 48 >>> 0) < 10 || c === 46) {  // digit (48–57) or '.' (46)

				// ─── parse one numeric token ──────────────────────────────────────
				var pv = 0;

				if (c !== 46) {
					// integer-first path: "2h", "30ms", "2.5h"
					pv = c - 48;  // value of first digit
					i++;
					while (i < len) {
						var _c = s.charCodeAt(i);
						var d = _c - 48 >>> 0;
						if (d >= 10) break;   // not a digit
						pv = pv * 10 + d;    // shift-accumulate
						i++;
					}
					// optional trailing decimal: "2.5h" — integer done, now ".5"
					if (i < len && s.charCodeAt(i) === 46) {
						i++;
						var fr = 0, div = 1;
						while (i < len) {
							var _c = s.charCodeAt(i);
							var d = _c - 48 >>> 0;
							if (d >= 10) break;
							fr = fr * 10 + d;
							div *= 10;
							i++;
						}
						if (div > 1) pv += fr / div;
						// "2." with nothing after stays as integer 2
					}
				} else {
					// dot-first path: ".5h"
					i++;
					var fr = 0, div = 1;
					while (i < len) {
						var _c = s.charCodeAt(i);
						var d = _c - 48 >>> 0;
						if (d >= 10) break;
						fr = fr * 10 + d;
						div *= 10;
						i++;
					}
					pv = div === 1 ? NaN : fr / div;  // lone "." → NaN → no match
				}

				if (pv === pv) {  // NaN guard (NaN !== NaN) — lone "." produces NaN
					// skip optional spaces between number and notation ("2 hours" — up to 3)
					var sp = 0;
					while (i < len && s.charCodeAt(i) === 32 && sp < 3) { i++; sp++; }

					if (i < len) {
						var c0 = s.charCodeAt(i);  // first char of potential notation

						if (c0 === 32 || (c0 - 48 >>> 0) < 10 || c0 === 46) {
							// c0 is digit, dot or space — not a notation start.
							// Absorb remaining digits/dots ("123 456" → skip second number).
							while (i < len) {
								var _c = s.charCodeAt(i);
								if ((_c - 48 >>> 0) < 10 || _c === 46) i++;
								else break;
							}
						} else {
							// ─── notation dispatch ────────────────────────────────
							// Each entry: check c0 + optional subsequent chars + boundary.
							// On match: i += elen, v += pv * multiplier, mc++, break match.
							match: {
${lookupCode}
							}
						}
					}
				}
				continue;
			}

			i++;  // skip non-digit, non-dot char (space between tokens, etc.)
		}

		// ─── fallback: mc===0 → no notation matched → try Number() ───────────────
		if (mc === 0) {
			var n = +str;
			return n !== n ? null : n;
		}
		return neg ? -v : v;
	`;

	return craftFunction<ParseFunction>('fastParseV25', [ 'str' ], source, { BOUND: boundaryArr });
}
