name: Eslint, mocha tests, and benchs

on:
  push:
    branches: [ update ]
  pull_request:
    branches: [ update ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - name: "Install dependencies"
      run: npm i

    - name: "Run eslint"
      run: npm run lint

    - name: "Run mocha tests"
      run: npm run mocha

    - name: "Run benchs"
      run: npm run bench && npm run bench
